name: Release LibOrbitSearch

on:
  push:
    branches: [main]
    paths:
      - LibOrbitSearch/LibOrbitSearch-1.0/**
      - '!LibOrbitSearch/LibOrbitSearch-1.0/**/README.md'
      - LibOrbitSearch/.pkgmeta
      - LibOrbitSearch/LICENSE
      - .github/workflows/release-search.yml
      - .github/workflows/release-library.yml
      - .scripts/release-library.py
      - .gitattributes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/release-library.yml
    with:
      library: LibOrbitSearch
